### ISSUE TITLE
Is there a way to get the Expr object working?

### ISSUE THREAD

**Issue by wolphox** [hagish/kalimba#8]
Hi, I just used Kalimba for an Android program in Unity. Kalimba is great!

I had trouble using Expr in my program though. I was only able to produce sound when I replaced any Expr object I had with alternative objects. I did a search through the repository and saw mentions of the Expr object but wasn't able to understand if it was implemented and suppose to work. I figure I'd ask here directly. Is there anything extra I have to do to make it work?

Best,
Jeff

Edit: Using Unity 5+ and PD Vanilla. Everything else worked as intended.

**Comment by 0xStarcat** [comment]
From what I've seen it looks like Expr is a proprietary object - licensed only for PD use or something like that.
